"""study

Revision ID: 7d0695cfe25e
Revises: e438bccc9589
Create Date: 2024-01-25 17:02:15.718302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d0695cfe25e'
down_revision = 'e438bccc9589'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('population_categorical_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('object_type', sa.Integer(), nullable=False),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_population_categorical_options'))
    )
    op.create_table('result_categorical_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('object_type', sa.Integer(), nullable=False),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_result_categorical_options'))
    )
    op.create_table('studies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_studies'))
    )
    op.create_table('study_categorical_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('object_type', sa.Integer(), nullable=False),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_study_categorical_options'))
    )
    op.create_table('variables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('default', sa.Boolean(), nullable=False),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.Column('var_type', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_variables'))
    )
    op.create_table('populations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_id', sa.Integer(), nullable=False),
    sa.Column('population', sa.Text(), nullable=False),
    sa.Column('longitudinal', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], name=op.f('fk_populations_study_id_studies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_populations'))
    )
    op.create_table('study_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variable_id', sa.Integer(), nullable=False),
    sa.Column('study_id', sa.Integer(), nullable=False),
    sa.Column('categorical', sa.Integer(), nullable=False),
    sa.Column('values', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['categorical'], ['study_categorical_options.id'], name=op.f('fk_study_data_categorical_study_categorical_options')),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], name=op.f('fk_study_data_study_id_studies')),
    sa.ForeignKeyConstraint(['variable_id'], ['variables.id'], name=op.f('fk_study_data_variable_id_variables')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_study_data'))
    )
    op.create_table('population_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variable_id', sa.Integer(), nullable=False),
    sa.Column('population_id', sa.Integer(), nullable=False),
    sa.Column('categorical', sa.Integer(), nullable=False),
    sa.Column('mean', sa.Float(), nullable=False),
    sa.Column('sd', sa.Float(), nullable=False),
    sa.Column('median', sa.Float(), nullable=False),
    sa.Column('p25', sa.Float(), nullable=False),
    sa.Column('p75', sa.Float(), nullable=False),
    sa.Column('n', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categorical'], ['population_categorical_options.id'], name=op.f('fk_population_data_categorical_population_categorical_options')),
    sa.ForeignKeyConstraint(['population_id'], ['populations.id'], name=op.f('fk_population_data_population_id_populations')),
    sa.ForeignKeyConstraint(['variable_id'], ['variables.id'], name=op.f('fk_population_data_variable_id_variables')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_population_data'))
    )
    op.create_table('subpopulations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('population_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('object_type', sa.Integer(), nullable=False),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['population_id'], ['populations.id'], name=op.f('fk_subpopulations_population_id_populations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subpopulations'))
    )
    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variable_id', sa.Integer(), nullable=False),
    sa.Column('categorical', sa.Integer(), nullable=False),
    sa.Column('population_id', sa.Integer(), nullable=False),
    sa.Column('subpopulation_id', sa.Integer(), nullable=False),
    sa.Column('result', sa.Text(), nullable=False),
    sa.Column('mean', sa.Float(), nullable=False),
    sa.Column('sd', sa.Float(), nullable=False),
    sa.Column('n', sa.Integer(), nullable=False),
    sa.Column('data_string', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['categorical'], ['result_categorical_options.id'], name=op.f('fk_results_categorical_result_categorical_options')),
    sa.ForeignKeyConstraint(['population_id'], ['populations.id'], name=op.f('fk_results_population_id_populations')),
    sa.ForeignKeyConstraint(['subpopulation_id'], ['subpopulations.id'], name=op.f('fk_results_subpopulation_id_subpopulations')),
    sa.ForeignKeyConstraint(['variable_id'], ['variables.id'], name=op.f('fk_results_variable_id_variables')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_results'))
    )
    op.create_table('subpopulation_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variable_id', sa.Integer(), nullable=False),
    sa.Column('categorical', sa.Integer(), nullable=False),
    sa.Column('mean', sa.Float(), nullable=False),
    sa.Column('sd', sa.Float(), nullable=False),
    sa.Column('n', sa.Integer(), nullable=False),
    sa.Column('data_string', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['categorical'], ['subpopulations.id'], name=op.f('fk_subpopulation_data_categorical_subpopulations')),
    sa.ForeignKeyConstraint(['variable_id'], ['variables.id'], name=op.f('fk_subpopulation_data_variable_id_variables')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subpopulation_data'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subpopulation_data')
    op.drop_table('results')
    op.drop_table('subpopulations')
    op.drop_table('population_data')
    op.drop_table('study_data')
    op.drop_table('populations')
    op.drop_table('variables')
    op.drop_table('study_categorical_options')
    op.drop_table('studies')
    op.drop_table('result_categorical_options')
    op.drop_table('population_categorical_options')
    # ### end Alembic commands ###
